name: development environment
on:
  pull_request:
    paths:
    - 'Brewfile'
    - 'Makefile'
    - '.github/workflows/development-environment.yml'
    - 'scripts/*'
    - 'src/sentry/runner/commands/devserver.py'
    - 'src/sentry/runner/commands/devservices.py'

jobs:
  dev-environment:
    name: python set up
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables & others
        if: ${{ runner.os == 'macOS' }}
        shell: bash
        # Setting the SHELL to zsh makes this machine more like a developer's machine
        run: |
          echo "HOMEBREW_CACHE=`brew --cache`" >> $GITHUB_ENV
          echo "SHELL=/bin/zsh" >> $GITHUB_ENV
          touch "$HOME/.zshrc"
          echo "VOLTA_HOME=$HOME/.volta" >> $GITHUB_ENV
          echo "PATH=$HOME/.volta/bin:$PATH" >> $GITHUB_ENV
          mv Brewfile.automation.lock.json Brewfile.lock.json

      - name: Cache (brew)
        uses: actions/cache@v2
        if: ${{ runner.os == 'macOS' }}
        with:
          path: $HOMEBREW_CACHE
          key: ${{ runner.os }}-brew-${{ hashFiles('Brewfile.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-brew

      - name: Install prerequisites
        if: ${{ runner.os == 'macOS' }}
        # Depending on the host watchman will not install (read: intermittent issue),
        # thus, we mark this as continue-on-error
        continue-on-error: true
        # Xcode CLI & brew are already installed, thus, no need to call xcode-select install
        # XXX: Can the Brew set up be cached?
        run: |
          brew install pyenv

      - name: Install Python (via Pyenv)
        id: python-version
        shell: bash
        # XXX: Can we cache the installed Python environments?
        # XXX: It's unfortunate we need to call pyenv init - to make the Python version be switched correctly
        run: |
          make setup-pyenv
          source "$HOME/.zshrc"
          [[ $(which python) == /usr/bin/python ]] && echo "It fails to set correct Python" && exit 1
          eval "$(pyenv init -)"
          echo "::set-output name=python-version::$(python -V  | sed s/Python\ //g)"

      - name: Setup pip
        uses: ./.github/actions/setup-pip
        id: pip

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.pip.outputs.pip-cache-dir }}
            ~/.pyenv
          key: ${{ runner.os }}-pip-py${{ steps.python-version.outputs.python-version }}-${{ hashFiles('**/requirements-*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-py${{ steps.python-version.outputs.python-version }}

      - name: Set up development environment (as per docs)
        # XXX: It's unfortunate we need to call pyenv init - to make the Python version be switched correctly
        run: |
          python -V
          cat "$HOME/.zshrc"
          eval "$(pyenv init -)"
          python -V
          python -m venv .venv
          source .venv/bin/activate
          make install-py-dev
          make setup-git
          curl https://get.volta.sh | bash

      - name: Set up Sentry and others
        # We cannot call make bootstrap directly since run-dependent-services requires some Docker magic.
        # We have the magic in the getsentry/bootstrap-develop. We will handle this situation in the next pass of this.
        # make init-config will *not* prompt about overwriting ~/.sentry/config.yml' since we're on a pristine state
        # We cannot test the git hooks until the `sentry.lint.engine` gets installed
        run: |
          source .venv/bin/activate
          make develop init-config
