# Dispatch a request to getsentry to run getsentry test suites
name: getsentry dispatcher

on:
  # XXX: We are using `pull_request_target` instead of `pull_request` because we want
  # this to run on forks.  It allows forks to access secrets safely by
  # only running workflows from the main branch. Prefer to use `pull_request` when possible.
  #
  # See https://github.com/getsentry/sentry/pull/21600 for more details
  # TODO: this needs to be pull_request_target
  pull_request:

jobs:
  dispatch:
    name: getsentry dispatch
    runs-on: ubuntu-16.04
    steps:
      # Need to checkout just for `github/file-filters.yml`
      - uses: actions/checkout@v2

      - name: Check for frontend file changes
        uses: getsentry/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

      - name: getsentry token
        uses: getsentry/action-github-app-token@v1
        id: getsentry
        with:
          app_id: ${{ secrets.SENTRY_INTERNAL_APP_ID }}
          private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}

      - name: Dispatch getsentry frontend tests
        uses: actions/github-script@v3
        with:
          github-token: ${{ steps.getsentry.outputs.token }}
          script: |
            const DISPATCHES = [{
              {
                workflow: 'js-build-and-lint.yml',
                pathFilterName: 'frontend',
              },
              {
                workflow: 'backend-test.yml',
                pathFilterName: 'backend_dependencies',
              }
            ];

            const shouldSkip = {
              frontend: ${{ steps.changes.outputs.frontend != 'true' }},
              backend_dependencies: ${{ steps.changes.outputs.backend_dependencies != 'true' }},
            };

            DISPATCHES.forEach(({workflow, pathFilterName}) => {
              github.actions.createWorkflowDispatch({
                owner: 'getsentry',
                repo: 'getsentry',
                workflow_id: workflow,
                ref: 'build/ci/add-backend-dependencies-test', // TODO: this needs to be 'master'
                inputs: {
                  skip: shouldSkip[pathFilterName],
                  'sentry-sha': '${{ github.event.pull_request.head.sha }}',
                }
              })
            });
